services:
  backend: 
    image: batch-6:7
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - path: .env
        required: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U batch6"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - batch6:/var/lib/postgresql/data
volumes:
  batch6: